name: factorpol
channels:
  - openeye
  - anaconda
  - psi4
  - conda-forge
dependencies:
  - psi4
  - cudatoolkit=11
  - openeye-toolkits
  - openff-recharge
  - openff-toolkit
  - openmm
  - openmmforcefields=0.11.2
  - pip:
    - ambertools
    - ray
    - sqlalchemy-utils
