name: docs
channels:
  - conda-forge
dependencies:
      # Base depends
  - python
  - pip
  - scipy
  - numpy
  - pint
  - sphinx
  - sphinx_rtd_theme
  - openff-toolkit-base >=0.11
  - openff-recharge
  - openff-units
  - sqlalchemy
  - parmed
  - lxml
  - openmmforcefields
  - ambertools
  - pip:
      - sqlalchemy_utils
      - ray
